##############################################################################
# Genome and project-specific files that will change from project-to-project
##############################################################################

# GTF file for the genome build you would like to use
gtf_file:
 /home/groups/mghayden/tools/refgenomes/GRCh38/gencode/release_34/gencode.v34.chr_patch_hapl_scaff.annotation.gtf
 #/scg/apps/data/refgenomes/GRCh38/gencode/release_34/gencode.v34.chr_patch_hapl_scaff.annotation.gtf
 #/labs/mghayden/gbarisano/annot_gtf/Homo_sapiens.GRCh38.110.chr_patch_hapl_scaff.gtf
    
# Bed file for rseqc function read_distribution
bed_file:
  /home/groups/mghayden/tools/snakemake_tools/gencode.v34.bed
 #/labs/mghayden/Maxine/snakemake/tools/gencode.v34.bed
# Pre-built star indexes for hg38
star_index:
  /home/groups/mghayden/tools/star/index/GRCh38/gencode/release_34/2.7.4a
 #/scg/apps/data/star/index/GRCh38/gencode/release_34/2.7.4a

exon_gtf:
  /home/groups/mghayden/tools/snakemake_tools/gencode.housekeeping_genes.exon.gtf
  #/labs/mghayden/Maxine/snakemake/tools/gencode.housekeeping_genes.exon.gtf
genome:
  /home/groups/mghayden/tools/refgenomes/GRCh38/gencode/release_34/GRCh38.p13.genome.fa
  #/scg/apps/data/refgenomes/GRCh38/gencode/release_34/GRCh38.p13.genome.fa
ens2geneID:
  /home/groups/mghayden/tools/snakemake_tools/biomart_ensembl_geneid.txt
  #/labs/mghayden/Maxine/snakemake/tools/biomart_ensembl_geneid.txt

####################################################################
# Tool-specific files that will not change from project-to-project
####################################################################

# Pre-built genome indexes for various organisms which we will screen against to look for contamination
fqscreen_conf:
 /home/groups/mghayden/tools/snakemake_tools/fastq_screen_new.conf
 #/labs/mghayden/Maxine/snakemake/tools/fastq_screen_new.conf
# Paths to various tools which are used in this pipeline
star_tool:
  /home/groups/mghayden/software/star/2.7.10a/bin/Linux_x86_64_static/STAR
  #/scg/apps/software/star/2.7.10a/bin/Linux_x86_64_static/STAR
sickle_tool:
  /home/groups/mghayden/software/sickle/1.33/sickle
  #/scg/apps/software/sickle/1.33/sickle
picard_tool:
  /home/groups/mghayden/software/picard/2.27.5/picard.jar
  #/scg/apps/software/picard/2.27.5/picard.jar
bamstats_tool:
  /home/groups/mghayden/software/bamstats/1.25/BAMStats-1.25.jar
  #/scg/apps/software/bamstats/1.25/BAMStats-1.25.jar

##########################################
# Important project-specific paths/files
##########################################

# Metadata needed for differential expression analysis
omic_meta_data:
    /scratch/users/barisano/CSFseq/ALL_star/metadata_CSF_Seq_ALL.txt
    #/labs/mghayden/gbarisano/rnaseq_processing/thy_2024.05.13/metadata.txt
    #/labs/mghayden/gbarisano/rnaseq_processing/ohsu_2024.04.15/metadata.txt
    #/labs/mghayden/gbarisano/rnaseq_processing/rtaiwo_2024.01.31/metadata.txt
  #/labs/mghayden/gbarisano/rnaseq_processing/rtaiwo_2023.10.27/metadata.txt
 #/labs/mghayden/gbarisano/snakemake_test/run_test_2023.09.16/metadata_test.txt
 #/labs/mghayden/Maxine/snakemake/tools/metadata_CSF_Seq.txt

#############################################################################################
# Project-specific specifications you will need to make prior to submission of the pipeline
#############################################################################################

project_id:
  CSF_Seq
assembly:
  hg38.90
#whatever name is the baseline name in the column used for the linear model
TE_baseline:
 NonCancer_CTRL
# option to print GO term tree (0/1)
printTree:
  1
## fold change cutoff (not log2 transformed) for GO analysis and volcano pot
FC:
  2
## FDR adjusted p-value cutoff for GO analysis and volcano plot
adjp:
  0.01
## The column name of the characteristic you would like to do DE on. Example: Diagnosis, genotype, etc. This must be a column in your omic_meta_data. 
linear_model:
  Group
seq_layout:
  PE
#column name of whatever the sample id column is
sample_id:
  Sample
### If you would like to colour your QC plots by an RColorBrewer palette, list that palette under the rcolorbrewer parameter, otherwise, write "NA"
### If you would like to colour your QC plots by specific colours, please list them under the discrete category, with one colour for each bullet point
#### The discrete colours will be assigned to your Conditions (ie. linear_model) in the order that they show up in your metadata table, when it is ordered alphabetically by sample ID
#### There must be the same number of colours listed as there are Conditions
### If no options are specified, the default ggplot2 colours are used
colors:
  rcolorbrewer:
    - Paired
  discrete:
    - NA
